### ISSUE TITLE
Make HttpClient static too

### ISSUE THREAD

**Issue by nzthiago** [syedhassaanahmed/azure-event-driven-data-pipeline#1]
Awesome work, thank you for sharing all of this! Was reading through the blog post and noticed this line:
https://github.com/syedhassaanahmed/azure-event-driven-data-pipeline/blob/master/azure-functions/ConsumerEgressFuncs/ConsumerEgressFuncs.cs#L64

Shouldn't it be declared as a static variable too, like DocumentClient? 
https://github.com/Azure/azure-functions-host/wiki/Managing-Connections#httpclient

I didn't want to assume without context so thought I'd ask via this issue.

**Comment by syedhassaanahmed** [comment]
@nzthiago Old habits die hard :) .. 100% Agreed with you. Thanks a lot for raising this. Just fixed it.
